<?php

$this->headLink()->prependStylesheet($this->baseUrl() . '/js/mootools/3rdpart/zwebox/themes/default/zwebox.ie6.css', 'screen', 'IE6');
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/mootools/3rdpart/zwebox/themes/default/zwebox.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/menu.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/layout.css');
$this->headLink()->prependStylesheet($this->baseUrl() . '/css/main.css');
$this->headLink()->prependStylesheet('http://fonts.googleapis.com/css?family=Lora:400italic,700italic');

$this->headScript()->prependFile($this->baseUrl() . '/js/mootools/3rdpart/zwebox/zwe-box.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/mootools/3rdpart/overlay/Overlay.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/main.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/mootools/powertools-1.1.1.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/mootools/mootools-more-1.4.0.1.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/mootools/mootools-core-1.4.4.js');

$menuXML = new SimpleXMLElement($this->navigation()->menu()->setMaxDepth(-1));
$menuLis = $menuXML->xpath('/ul/li');
$menuLeft = $menuLis[0]->asXML() . $menuLis[1]->asXML() . $menuLis[2]->asXML();
$menuRight = $menuLis[3]->asXML() . $menuLis[4]->asXML() . $menuLis[5]->asXML();

$breadcrumbs = $this->navigation()->breadcrumbs()->setRenderInvisible(true)->setSeparator(' &nbsp;/&nbsp; ');

$container = APPLICATION_PATH . (Zend_Controller_Front::getInstance()->getRequest()->getModuleName() == 'default' ? '' : '/modules/' . Zend_Controller_Front::getInstance()->getRequest()->getModuleName()) . '/views/layouts/container.phtml';

?>
<?= $this->doctype() . "\n" ?>
<html>

<head>
    <?= $this->headTitle() . "\n" ?>
    <?= str_replace("\n", "\n    ", $this->headMeta()) . "\n" ?>
    <?= str_replace("\n", "\n    ", $this->headLink()) . "\n" ?>
    <?= str_replace("\n", "\n    ", $this->headStyle()) . "\n" ?>
    <?= str_replace(array("\n", ">script>"), array("\n    ", "></script>"), $this->headScript()) . "\n" ?>
    <script type="text/javascript">
        var __BASEURL__ = "<?= $this->baseUrl() ?>";
        var __BASEURL__LANG__ = __BASEURL__ + '/' + "<?= $this->escape(Zend_Registry::get('Zend_Locale')->getLanguage()) ?>";
    </script>
</head>

<body>
    <a id="top"></a>
    <div id="layout-top">
        <div id="layout-top-right">
            <ul class="no-list">
                <li>
                    <a href="http://www.facebook.com/zweer" target="_blank">
                        <?= $this->img('/images/social_network/facebook_16.png', array('alt' => $this->translate('Follow me on') . ' Facebook', 'title' => $this->translate('Follow me on') . ' Facebook')) ?>
                    </a>
                </li>
                <li>
                    <a href="https://plus.google.com/u/0/111514767804391444725" target="_blank">
                        <?= $this->img('/images/social_network/google_plus_16.png', array('alt' => $this->translate('Follow me on') . ' Google+', 'title' => $this->translate('Follow me on') . ' Google+')) ?>
                    </a>
                </li>
                <li>
                    <a href="https://twitter.com/#!/dotzweer" target="_blank">
                        <?= $this->img('/images/social_network/twitter_16.png', array('alt' => $this->translate('Follow me on') . ' Twitter', 'title' => $this->translate('Follow me on') . ' Twitter')) ?>
                    </a>
                </li>
                <li>
                    <a href="http://www.youtube.com/zweer" target="_blank">
                        <?= $this->img('/images/social_network/youtube_16.png', array('alt' => $this->translate('Follow me on') . ' Youtube', 'title' => $this->translate('Follow me on') . ' Youtube')) ?>
                    </a>
                </li>
            </ul>
        </div>

        <div id="layout-top-left">
            <ul class="no-list">
<?php if(!Zwe_Auth::getInstance()->hasIdentity()) : ?>
                <li id="layout-top-left-login">
                    <a href="<?= $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'index'), 'default') ?>.html" id="login-open">
                        <?= $this->img('/images/icons/unlock_24x24.png', array('alt' => $this->translate('Login'), 'title' => $this->translate('Login'))) ?>
                    </a>
                </li>
<?php else : ?>
                <li>
                    <a href="<?= $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'logout'), 'default') ?>">
                        <?= $this->img('/images/icons/lock_24x24.png', array('alt' => $this->translate('Logout'), 'title' => $this->translate('Logout'))) ?>
                    </a>
                </li>
                <?php if(Zwe_Auth::getInstance()->getIdentity()->isAllowedAny('admin')) : ?>
                <li class="menulike-toexpand">
                    <?= $this->img('/images/icons/gear_wheel_24x24.png', array('alt' => $this->translate('Admin'))) ?>
                    <ul>
                        <?php foreach(Zwe_Auth::getInstance()->getIdentity()->getAllowed('admin') as $subAdmin) : ?>
                        <?php $subAdmin = substr($subAdmin, strlen('admin_')); ?>
                        <li>
                            <a href="<?= $this->url(array('module' => 'admin', 'controller' => $subAdmin, 'action' => 'index'), 'default') ?>"><?= ucfirst($this->translate($subAdmin)) ?></a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
                <?php endif; ?>
                <li>
                    <?= $this->translate('Hi') ?> <?= Zend_Auth::getInstance()->getIdentity()->Username ?>
                </li>
<?php endif; ?>
            </ul>
        </div>
    </div>

    <div id="layout-header-middle">
        <div id="layout-header-top">
            <div id="layout-header-bottom">
                <div id="layout-header">
                    <div id="layout-header-logo">
                        <a href="<?= $this->url(array('controller' => 'index', 'action' => 'index', 'module' => 'default'), 'default') ?>">
                            <?= $this->img('/images/layout/title.png', array('alt' => 'noliv')) ?>
                        </a>
                    </div>

                    <div id="layout-header-menu">
                        <div id="layout-header-menu-left">
                            <ul><?= $menuLeft ?></ul>
                        </div>
                        <div id="layout-header-menu-right">
                            <ul><?= $menuRight ?></ul>
                        </div>
                    </div>

                    <div id="layout-header-title">
                        <div id="layout-header-title-search">
                            <input type="text" value="search" name="search">
                            <a href="#">
                                <?= $this->img('/images/layout/search-icon.png', array('alt' => 'find')) ?>
                            </a>
                        </div>
                        <div id="layout-header-title-breadcrumbs">
                            <?php if(strlen($breadcrumbs)) : ?>
                            <a title="Home" href="<?= $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), 'default') ?>">Home</a> &nbsp;/&nbsp; <?= $breadcrumbs ?>
                            <?php endif; ?>
                        </div>
                        <h1><?= $this->title ?></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="layout-container" class="autoclear">
        <?php if(file_exists($container)) : include($container); else : ?>
        <?= $this->layout()->content ?>
        <?php endif; ?>
    </div>

    <div id="layout-additional-footer-bg">
        <div id="layout-additional-footer">

        </div>
    </div>

    <div id="layout-footer-bg">
        <div id="layout-footer">


            <div id="layout-footer-small-footer">
                <div id="layout-footer-small-footer-gototop">
                    <a href="#top">
                        <span><?= $this->translate('Go to top') ?></span>
                    </a>
                </div>

                <div id="layout-footer-small-footer-right">
                    <ul class="no-list">
                        <li>
                            <?= $this->translate('Contact me') ?> @ <a href="mailto:<?= Zend_Registry::get('parameters')->registry->email ?>"><?= Zend_Registry::get('parameters')->registry->email ?></a>
                        </li>
                    </ul>
                </div>
                <div id="layout-footer-small-footer-left">
                    <ul class="no-list">
                        <li>
                            Niccol&ograve; Olivieri
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>
</html>