<div class="layout-container-2third">
    <?= $this->layout()->content ?>
</div>

<div class="layout-container-1third layout-container-last">
    <div class="sidebar">
        <div class="sidebar-bottom">
            <div class="sidebar-top">
                <h2><?= $this->translate('Categories') ?></h2>
                <h2><?= $this->translate('Archive') ?></h2>
            </div>
        </div>
    </div>
</div>