<?php

$this->form->setAction($this->url())
           ->getElement('list')->setLabel('Permission')->setAttrib('id', 'privileges_list');
$this->form->getElement('name')->setLabel('Group')->setAttrib('id', 'privileges_resources');

$this->headScript()->appendFile($this->baseUrl() . '/js/privilege_resource.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/tree.css');

?>
<?= $this->form ?>
<?= $this->tree2ulPrivilege($this->resources) ?>