<?php

/**
 * @file application/views/scripts/error/error.phtml
 * La view per la pagina di errore.
 *
 * @category    application
 * @package     Default
 * @subpackage  View_Script
 * @version     $Id: error.phtml 40 2011-07-23 11:31:49Z flicofloc@gmail.com $
 */

$this->title = "An error occurred";
$this->headTitle()->append($this->message);

?>
<h2><?= $this->message ?></h2>
<?php if (isset($this->exception)): ?>
  
<h3>Exception information:</h3>
<p>
    <strong>Message:</strong> <?= $this->exception->getMessage() ?>
</p>

<h3>Stack trace:</h3>
<pre><?= $this->exception->getTraceAsString() ?>
</pre>

<h3>Request Parameters:</h3>
<pre><?= $this->escape(var_export($this->request->getParams(), true)) ?>
</pre>

<?php endif ?>
