<?php

/**
 * @file application/views/scripts/error/error.phtml
 * La view per la pagina di errore.
 *
 * @category    application
 * @package     Default
 * @subpackage  View_Script
 * @version     $Id: error.phtml 40 2011-07-23 11:31:49Z flicofloc@gmail.com $
 */

$this->title = $this->message;
$this->headTitle()->append($this->message);

$this->headLink()->appendStylesheet($this->baseUrl() . '/css/error.css');

?>
<div id="layout-error-container" class="autoclear">
    <h2><?= $this->translate('Oops') ?>...</h2>
    <h4><?= $this->translate(Zwe_Controller_Action_Error::ERROR_MESSAGE . $this->code) ?>.</h4>
    <?php if($this->code == 404) : ?>
    <div>
        <?= $this->translate('You can visit my other pages') ?>:
        <?= $this->navigation()->menu()->setMaxDepth(0) ?>
    </div>
    <?php endif; ?>
</div>
<?php if (isset($this->exception)): ?>

<h3><?= $this->translate('Exception information') ?>:</h3>
<p>
    <strong><?= $this->translate('Message') ?>:</strong> <?= $this->exception->getMessage() ?>
</p>

<br />

<h3><?= $this->translate('Stack trace') ?>:</h3>
<pre><?= $this->exception->getTraceAsString() ?></pre>

<h3><?= $this->translate('Route used') ?>:</h3>
<pre><?php try{ echo $this->escape(Zend_Controller_Front::getInstance()->getRouter()->getCurrentRouteName()); }catch(Exception $e){ echo $e->getMessage(); } ?></pre>

<h3><?= $this->translate('Base URL') ?>:</h3>
<pre><?= $this->escape($this->request->getBaseUrl()) ?></pre>

<h3><?= $this->translate('Request Parameters') ?>:</h3>
<pre><?= $this->escape(var_export($this->request->getParams(), true)) ?></pre>

<h3><?= $this->translate('Language') ?>:</h3>
<pre><?= $this->escape(Zend_Registry::get('Zend_Locale')->getLanguage()) ?></pre>

<?php if(Zend_Auth::getInstance()->hasIdentity()) : ?>
<h3><?= $this->translate('Acl') ?>:</h3>
<pre><?= $this->escape(print_r(Zend_Auth::getInstance()->getIdentity()->Acl, 1)) ?></pre>
<?php endif; ?>

<?php endif ?>
