<?php

/**
 * @file application/views/scripts/error/error.phtml
 * La view per la pagina di errore.
 *
 * @category    application
 * @package     Default
 * @subpackage  View_Script
 * @version     $Id: error.phtml 40 2011-07-23 11:31:49Z flicofloc@gmail.com $
 */

$this->title = $this->message;
$this->headTitle()->append($this->message);

$this->headLink()->appendStylesheet($this->baseUrl() . '/css/error.css');

?>
<div id="layout-error-container" class="autoclear">
    <h2><?= $this->translate('Oops') ?>...</h2>
    <h4><?= $this->translate(Zwe_Controller_Action_Error::ERROR_MESSAGE . $this->code) ?>.</h4>
    <?php if($this->code == 404) : ?>
    <div>
        You can visit our other pages: <br /><br />
        <?= $this->navigation()->menu()->setMaxDepth(0) ?>
    </div>
    <?php endif; ?>
</div>
<?php if (isset($this->exception)): ?>

<h3>Exception information:</h3>
<p>
    <strong>Message:</strong> <?= $this->exception->getMessage() ?>
</p><br />

<h3>Stack trace:</h3>
<pre><?= $this->exception->getTraceAsString() ?>
</pre>

<h3>Request Parameters:</h3>
<pre><?= $this->escape(var_export($this->request->getParams(), true)) ?>
</pre>

<h3>Language:</h3>
<pre><?= Zend_Registry::get('Zend_Locale')->getLanguage() ?>
</pre>

<?php endif ?>
